global using System.ComponentModel.DataAnnotations;
global using CG.Orange.Directors;
global using CG.Orange.Managers;
global using CG.Orange.Seeding.Options;
global using CG.Validations;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using CG.Orange.Seeding.Directors;
global using Microsoft.Extensions.DependencyInjection;