global using Azure.Security.KeyVault.Secrets;
global using CG.Blazor.Plugins;
global using CG.Orange.Providers;
global using CG.Validations;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel.DataAnnotations;
